---
---
# Jenkins bootstrap playbook (idempotent). This playbook prepares a host
# with Docker and runs the official Jenkins LTS image. Intended for demo/dev.

- name: Provision Jenkins host with Docker and run Jenkins container
  hosts: jenkins
  become: true
  vars:
    jenkins_home: /var/jenkins_home
    jenkins_port: 8080

  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - git
          - curl
          - python3
        state: present

    - name: Install docker (best-effort)
      package:
        name: docker
        state: present
      ignore_errors: true

    - name: Ensure docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Ensure jenkins home exists
      file:
        path: "{{ jenkins_home }}"
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    - name: Run Jenkins container (idempotent)
      community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk17
        state: started
        restart_policy: always
        published_ports:
          - "{{ jenkins_port }}:8080"
          - "50000:50000"
        volumes:
          - "{{ jenkins_home }}:/var/jenkins_home"

  # Note: This playbook is intentionally simple for demo projects. For
  # production, secure Jenkins, manage credentials/secrets with Vault and
  # run behind an ingress with TLS.
